include:
  - board: nice_nano//zmk
    shield: mriya_left nice_view_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano//zmk
    shield: mriya_right nice_view_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: xiao_ble//zmk
    shield: mriya_dongle prospector_adapter
  - board: nice_nano//zmk
    shield: settings_reset
  - board: xiao_ble//zmk
    shield: settings_reset

